# GNU Make project makefile autogenerated by GENie
ifndef config
  config=debug32
endif

ifndef verbose
  SILENT = @
endif

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(MAKESHELL)))
  SHELLTYPE := posix
endif

ifeq (posix,$(SHELLTYPE))
  MKDIR = $(SILENT) mkdir -p "$(1)"
  COPY  = $(SILENT) cp -fR "$(1)" "$(2)"
  RM    = $(SILENT) rm -f "$(1)"
else
  MKDIR = $(SILENT) mkdir "$(subst /,\\,$(1))" 2> nul || exit 0
  COPY  = $(SILENT) copy /Y "$(subst /,\\,$(1))" "$(subst /,\\,$(2))"
  RM    = $(SILENT) del /F "$(subst /,\\,$(1))" 2> nul || exit 0
endif

CC  = gcc
CXX = g++
AR  = ar

ifndef RESCOMP
  ifdef WINDRES
    RESCOMP = $(WINDRES)
  else
    RESCOMP = windres
  endif
endif

ifeq ($(config),debug32)
  OBJDIR              = ../../../../linux_gcc/obj/x32/Debug
  TARGETDIR           = ../../../../linux_gcc/bin/x32/Debug
  override TARGET              = $(TARGETDIR)/libutils.a
  DEFINES            += -DMAME_DEBUG -DMAME_PROFILER -DCRLF=2 -DLSB_FIRST -DFLAC__NO_DLL -DPUGIXML_HEADER_ONLY -DNATIVE_DRC=drcbe_x86 -DLUA_COMPAT_ALL -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -DUTF8PROC_STATIC
  INCLUDES           += -I"../../../../../src/osd" -I"../../../../../src/lib/util" -I"../../../../../3rdparty" -I"../../../../../3rdparty/expat/lib" -I"../../../../../3rdparty/zlib" -I"../../../../../3rdparty/libflac/include" -I"../../../../../3rdparty/utf8proc"
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -m32 -pipe -Werror -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -Wno-error=attributes -Wno-format-overflow -Wno-stringop-truncation -Wno-stringop-overflow -Wno-return-local-addr -m32
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -m32 -pipe -Werror -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -Wno-error=attributes -Wno-format-overflow -Wno-stringop-truncation -Wno-stringop-overflow -Wno-return-local-addr -m32 -std=gnu99 -Wpointer-arith -Wstrict-prototypes -Wbad-function-cast
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -m32 -std=c++17 -pipe -Werror -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -Wno-error=attributes -Wno-format-overflow -Wno-stringop-truncation -Wno-stringop-overflow -Wno-return-local-addr -m32 -std=c++17 -Woverloaded-virtual -Wimplicit-fallthrough -Wno-class-memaccess -Wsuggest-override -flifetime-dse=1
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -m32 -pipe -Werror -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -Wno-error=attributes -Wno-format-overflow -Wno-stringop-truncation -Wno-stringop-overflow -Wno-return-local-addr -m32
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -m32 -std=c++17 -pipe -Werror -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -Wno-error=attributes -Wno-format-overflow -Wno-stringop-truncation -Wno-stringop-overflow -Wno-return-local-addr -m32 -std=c++17 -Wpointer-arith -Wimplicit-fallthrough
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -L"../../../../../../../../../usr/X11/lib" -L"../../../../../../../../../usr/X11R6/lib" -L"../../../../../../../../../usr/openwin/lib" -L"." -s -m32
  LIBDEPS            +=
  LDDEPS             +=
  LDRESP              =
  LIBS               += $(LDDEPS) -ldl -lrt -lSDL2 -lm -lpthread -lutil
  EXTERNAL_LIBS      +=
  LINKOBJS            = $(OBJECTS)
  LINKCMD             = $(AR)  -rcs $(TARGET)
  OBJRESP             =
  OBJECTS := \
	$(OBJDIR)/src/lib/util/avhuff.o \
	$(OBJDIR)/src/lib/util/aviio.o \
	$(OBJDIR)/src/lib/util/bitmap.o \
	$(OBJDIR)/src/lib/util/cdrom.o \
	$(OBJDIR)/src/lib/util/chd.o \
	$(OBJDIR)/src/lib/util/chdcd.o \
	$(OBJDIR)/src/lib/util/chdcodec.o \
	$(OBJDIR)/src/lib/util/corealloc.o \
	$(OBJDIR)/src/lib/util/corefile.o \
	$(OBJDIR)/src/lib/util/corestr.o \
	$(OBJDIR)/src/lib/util/coreutil.o \
	$(OBJDIR)/src/lib/util/delegate.o \
	$(OBJDIR)/src/lib/util/disasmintf.o \
	$(OBJDIR)/src/lib/util/dynamicclass.o \
	$(OBJDIR)/src/lib/util/flac.o \
	$(OBJDIR)/src/lib/util/harddisk.o \
	$(OBJDIR)/src/lib/util/hash.o \
	$(OBJDIR)/src/lib/util/hashing.o \
	$(OBJDIR)/src/lib/util/huffman.o \
	$(OBJDIR)/src/lib/util/ioprocs.o \
	$(OBJDIR)/src/lib/util/ioprocsfilter.o \
	$(OBJDIR)/src/lib/util/jedparse.o \
	$(OBJDIR)/src/lib/util/language.o \
	$(OBJDIR)/src/lib/util/md5.o \
	$(OBJDIR)/src/lib/util/msdib.o \
	$(OBJDIR)/src/lib/util/nanosvg.o \
	$(OBJDIR)/src/lib/util/opresolv.o \
	$(OBJDIR)/src/lib/util/options.o \
	$(OBJDIR)/src/lib/util/palette.o \
	$(OBJDIR)/src/lib/util/path.o \
	$(OBJDIR)/src/lib/util/path_to_regex.o \
	$(OBJDIR)/src/lib/util/plaparse.o \
	$(OBJDIR)/src/lib/util/png.o \
	$(OBJDIR)/src/lib/util/strformat.o \
	$(OBJDIR)/src/lib/util/timeconv.o \
	$(OBJDIR)/src/lib/util/un7z.o \
	$(OBJDIR)/src/lib/util/unicode.o \
	$(OBJDIR)/src/lib/util/unzip.o \
	$(OBJDIR)/src/lib/util/vbiparse.o \
	$(OBJDIR)/src/lib/util/vecstream.o \
	$(OBJDIR)/src/lib/util/wavwrite.o \
	$(OBJDIR)/src/lib/util/xmlfile.o \
	$(OBJDIR)/src/lib/util/zippath.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release32)
  OBJDIR              = ../../../../linux_gcc/obj/x32/Release
  TARGETDIR           = ../../../../linux_gcc/bin/x32/Release
  override TARGET              = $(TARGETDIR)/libutils.a
  DEFINES            += -DNDEBUG -DCRLF=2 -DLSB_FIRST -DFLAC__NO_DLL -DPUGIXML_HEADER_ONLY -DNATIVE_DRC=drcbe_x86 -DLUA_COMPAT_ALL -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -DUTF8PROC_STATIC
  INCLUDES           += -I"../../../../../src/osd" -I"../../../../../src/lib/util" -I"../../../../../3rdparty" -I"../../../../../3rdparty/expat/lib" -I"../../../../../3rdparty/zlib" -I"../../../../../3rdparty/libflac/include" -I"../../../../../3rdparty/utf8proc"
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -m32 -pipe -Werror -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -Wno-error=attributes -Wno-format-overflow -Wno-stringop-truncation -Wno-stringop-overflow -Wno-return-local-addr -m32
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -m32 -pipe -Werror -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -Wno-error=attributes -Wno-format-overflow -Wno-stringop-truncation -Wno-stringop-overflow -Wno-return-local-addr -m32 -std=gnu99 -Wpointer-arith -Wstrict-prototypes -Wbad-function-cast
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -m32 -std=c++17 -pipe -Werror -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -Wno-error=attributes -Wno-format-overflow -Wno-stringop-truncation -Wno-stringop-overflow -Wno-return-local-addr -m32 -std=c++17 -Woverloaded-virtual -Wimplicit-fallthrough -Wno-class-memaccess -Wsuggest-override -flifetime-dse=1
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -m32 -pipe -Werror -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -Wno-error=attributes -Wno-format-overflow -Wno-stringop-truncation -Wno-stringop-overflow -Wno-return-local-addr -m32
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -m32 -std=c++17 -pipe -Werror -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -Wno-error=attributes -Wno-format-overflow -Wno-stringop-truncation -Wno-stringop-overflow -Wno-return-local-addr -m32 -std=c++17 -Wpointer-arith -Wimplicit-fallthrough
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -L"../../../../../../../../../usr/X11/lib" -L"../../../../../../../../../usr/X11R6/lib" -L"../../../../../../../../../usr/openwin/lib" -L"." -s -m32
  LIBDEPS            +=
  LDDEPS             +=
  LDRESP              =
  LIBS               += $(LDDEPS) -ldl -lrt -lSDL2 -lm -lpthread -lutil
  EXTERNAL_LIBS      +=
  LINKOBJS            = $(OBJECTS)
  LINKCMD             = $(AR)  -rcs $(TARGET)
  OBJRESP             =
  OBJECTS := \
	$(OBJDIR)/src/lib/util/avhuff.o \
	$(OBJDIR)/src/lib/util/aviio.o \
	$(OBJDIR)/src/lib/util/bitmap.o \
	$(OBJDIR)/src/lib/util/cdrom.o \
	$(OBJDIR)/src/lib/util/chd.o \
	$(OBJDIR)/src/lib/util/chdcd.o \
	$(OBJDIR)/src/lib/util/chdcodec.o \
	$(OBJDIR)/src/lib/util/corealloc.o \
	$(OBJDIR)/src/lib/util/corefile.o \
	$(OBJDIR)/src/lib/util/corestr.o \
	$(OBJDIR)/src/lib/util/coreutil.o \
	$(OBJDIR)/src/lib/util/delegate.o \
	$(OBJDIR)/src/lib/util/disasmintf.o \
	$(OBJDIR)/src/lib/util/dynamicclass.o \
	$(OBJDIR)/src/lib/util/flac.o \
	$(OBJDIR)/src/lib/util/harddisk.o \
	$(OBJDIR)/src/lib/util/hash.o \
	$(OBJDIR)/src/lib/util/hashing.o \
	$(OBJDIR)/src/lib/util/huffman.o \
	$(OBJDIR)/src/lib/util/ioprocs.o \
	$(OBJDIR)/src/lib/util/ioprocsfilter.o \
	$(OBJDIR)/src/lib/util/jedparse.o \
	$(OBJDIR)/src/lib/util/language.o \
	$(OBJDIR)/src/lib/util/md5.o \
	$(OBJDIR)/src/lib/util/msdib.o \
	$(OBJDIR)/src/lib/util/nanosvg.o \
	$(OBJDIR)/src/lib/util/opresolv.o \
	$(OBJDIR)/src/lib/util/options.o \
	$(OBJDIR)/src/lib/util/palette.o \
	$(OBJDIR)/src/lib/util/path.o \
	$(OBJDIR)/src/lib/util/path_to_regex.o \
	$(OBJDIR)/src/lib/util/plaparse.o \
	$(OBJDIR)/src/lib/util/png.o \
	$(OBJDIR)/src/lib/util/strformat.o \
	$(OBJDIR)/src/lib/util/timeconv.o \
	$(OBJDIR)/src/lib/util/un7z.o \
	$(OBJDIR)/src/lib/util/unicode.o \
	$(OBJDIR)/src/lib/util/unzip.o \
	$(OBJDIR)/src/lib/util/vbiparse.o \
	$(OBJDIR)/src/lib/util/vecstream.o \
	$(OBJDIR)/src/lib/util/wavwrite.o \
	$(OBJDIR)/src/lib/util/xmlfile.o \
	$(OBJDIR)/src/lib/util/zippath.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug64)
  OBJDIR              = ../../../../linux_gcc/obj/x64/Debug
  TARGETDIR           = ../../../../linux_gcc/bin/x64/Debug
  override TARGET              = $(TARGETDIR)/libutils.a
  DEFINES            += -DPTR64=1 -DMAME_DEBUG -DMAME_PROFILER -DCRLF=2 -DLSB_FIRST -DFLAC__NO_DLL -DPUGIXML_HEADER_ONLY -DNATIVE_DRC=drcbe_x64 -DLUA_COMPAT_ALL -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -DUTF8PROC_STATIC
  INCLUDES           += -I"../../../../../src/osd" -I"../../../../../src/lib/util" -I"../../../../../3rdparty" -I"../../../../../3rdparty/expat/lib" -I"../../../../../3rdparty/zlib" -I"../../../../../3rdparty/libflac/include" -I"../../../../../3rdparty/utf8proc"
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -m64 -pipe -Werror -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -Wno-error=attributes -Wno-format-overflow -Wno-stringop-truncation -Wno-stringop-overflow -Wno-return-local-addr -m64
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -m64 -pipe -Werror -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -Wno-error=attributes -Wno-format-overflow -Wno-stringop-truncation -Wno-stringop-overflow -Wno-return-local-addr -m64 -std=gnu99 -Wpointer-arith -Wstrict-prototypes -Wbad-function-cast
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -m64 -std=c++17 -pipe -Werror -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -Wno-error=attributes -Wno-format-overflow -Wno-stringop-truncation -Wno-stringop-overflow -Wno-return-local-addr -m64 -std=c++17 -Woverloaded-virtual -Wimplicit-fallthrough -Wno-class-memaccess -Wsuggest-override -flifetime-dse=1
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -m64 -pipe -Werror -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -Wno-error=attributes -Wno-format-overflow -Wno-stringop-truncation -Wno-stringop-overflow -Wno-return-local-addr -m64
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -m64 -std=c++17 -pipe -Werror -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -Wno-error=attributes -Wno-format-overflow -Wno-stringop-truncation -Wno-stringop-overflow -Wno-return-local-addr -m64 -std=c++17 -Wpointer-arith -Wimplicit-fallthrough
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -L"../../../../../../../../../usr/X11/lib" -L"../../../../../../../../../usr/X11R6/lib" -L"../../../../../../../../../usr/openwin/lib" -L"." -s -m64
  LIBDEPS            +=
  LDDEPS             +=
  LDRESP              =
  LIBS               += $(LDDEPS) -ldl -lrt -lSDL2 -lm -lpthread -lutil
  EXTERNAL_LIBS      +=
  LINKOBJS            = $(OBJECTS)
  LINKCMD             = $(AR)  -rcs $(TARGET)
  OBJRESP             =
  OBJECTS := \
	$(OBJDIR)/src/lib/util/avhuff.o \
	$(OBJDIR)/src/lib/util/aviio.o \
	$(OBJDIR)/src/lib/util/bitmap.o \
	$(OBJDIR)/src/lib/util/cdrom.o \
	$(OBJDIR)/src/lib/util/chd.o \
	$(OBJDIR)/src/lib/util/chdcd.o \
	$(OBJDIR)/src/lib/util/chdcodec.o \
	$(OBJDIR)/src/lib/util/corealloc.o \
	$(OBJDIR)/src/lib/util/corefile.o \
	$(OBJDIR)/src/lib/util/corestr.o \
	$(OBJDIR)/src/lib/util/coreutil.o \
	$(OBJDIR)/src/lib/util/delegate.o \
	$(OBJDIR)/src/lib/util/disasmintf.o \
	$(OBJDIR)/src/lib/util/dynamicclass.o \
	$(OBJDIR)/src/lib/util/flac.o \
	$(OBJDIR)/src/lib/util/harddisk.o \
	$(OBJDIR)/src/lib/util/hash.o \
	$(OBJDIR)/src/lib/util/hashing.o \
	$(OBJDIR)/src/lib/util/huffman.o \
	$(OBJDIR)/src/lib/util/ioprocs.o \
	$(OBJDIR)/src/lib/util/ioprocsfilter.o \
	$(OBJDIR)/src/lib/util/jedparse.o \
	$(OBJDIR)/src/lib/util/language.o \
	$(OBJDIR)/src/lib/util/md5.o \
	$(OBJDIR)/src/lib/util/msdib.o \
	$(OBJDIR)/src/lib/util/nanosvg.o \
	$(OBJDIR)/src/lib/util/opresolv.o \
	$(OBJDIR)/src/lib/util/options.o \
	$(OBJDIR)/src/lib/util/palette.o \
	$(OBJDIR)/src/lib/util/path.o \
	$(OBJDIR)/src/lib/util/path_to_regex.o \
	$(OBJDIR)/src/lib/util/plaparse.o \
	$(OBJDIR)/src/lib/util/png.o \
	$(OBJDIR)/src/lib/util/strformat.o \
	$(OBJDIR)/src/lib/util/timeconv.o \
	$(OBJDIR)/src/lib/util/un7z.o \
	$(OBJDIR)/src/lib/util/unicode.o \
	$(OBJDIR)/src/lib/util/unzip.o \
	$(OBJDIR)/src/lib/util/vbiparse.o \
	$(OBJDIR)/src/lib/util/vecstream.o \
	$(OBJDIR)/src/lib/util/wavwrite.o \
	$(OBJDIR)/src/lib/util/xmlfile.o \
	$(OBJDIR)/src/lib/util/zippath.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release64)
  OBJDIR              = ../../../../linux_gcc/obj/x64/Release
  TARGETDIR           = ../../../../linux_gcc/bin/x64/Release
  override TARGET              = $(TARGETDIR)/libutils.a
  DEFINES            += -DPTR64=1 -DNDEBUG -DCRLF=2 -DLSB_FIRST -DFLAC__NO_DLL -DPUGIXML_HEADER_ONLY -DNATIVE_DRC=drcbe_x64 -DLUA_COMPAT_ALL -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -DUTF8PROC_STATIC
  INCLUDES           += -I"../../../../../src/osd" -I"../../../../../src/lib/util" -I"../../../../../3rdparty" -I"../../../../../3rdparty/expat/lib" -I"../../../../../3rdparty/zlib" -I"../../../../../3rdparty/libflac/include" -I"../../../../../3rdparty/utf8proc"
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -m64 -pipe -Werror -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -Wno-error=attributes -Wno-format-overflow -Wno-stringop-truncation -Wno-stringop-overflow -Wno-return-local-addr -m64
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -m64 -pipe -Werror -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -Wno-error=attributes -Wno-format-overflow -Wno-stringop-truncation -Wno-stringop-overflow -Wno-return-local-addr -m64 -std=gnu99 -Wpointer-arith -Wstrict-prototypes -Wbad-function-cast
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -m64 -std=c++17 -pipe -Werror -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -Wno-error=attributes -Wno-format-overflow -Wno-stringop-truncation -Wno-stringop-overflow -Wno-return-local-addr -m64 -std=c++17 -Woverloaded-virtual -Wimplicit-fallthrough -Wno-class-memaccess -Wsuggest-override -flifetime-dse=1
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -m64 -pipe -Werror -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -Wno-error=attributes -Wno-format-overflow -Wno-stringop-truncation -Wno-stringop-overflow -Wno-return-local-addr -m64
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -m64 -std=c++17 -pipe -Werror -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -Wno-error=attributes -Wno-format-overflow -Wno-stringop-truncation -Wno-stringop-overflow -Wno-return-local-addr -m64 -std=c++17 -Wpointer-arith -Wimplicit-fallthrough
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -L"../../../../../../../../../usr/X11/lib" -L"../../../../../../../../../usr/X11R6/lib" -L"../../../../../../../../../usr/openwin/lib" -L"." -s -m64
  LIBDEPS            +=
  LDDEPS             +=
  LDRESP              =
  LIBS               += $(LDDEPS) -ldl -lrt -lSDL2 -lm -lpthread -lutil
  EXTERNAL_LIBS      +=
  LINKOBJS            = $(OBJECTS)
  LINKCMD             = $(AR)  -rcs $(TARGET)
  OBJRESP             =
  OBJECTS := \
	$(OBJDIR)/src/lib/util/avhuff.o \
	$(OBJDIR)/src/lib/util/aviio.o \
	$(OBJDIR)/src/lib/util/bitmap.o \
	$(OBJDIR)/src/lib/util/cdrom.o \
	$(OBJDIR)/src/lib/util/chd.o \
	$(OBJDIR)/src/lib/util/chdcd.o \
	$(OBJDIR)/src/lib/util/chdcodec.o \
	$(OBJDIR)/src/lib/util/corealloc.o \
	$(OBJDIR)/src/lib/util/corefile.o \
	$(OBJDIR)/src/lib/util/corestr.o \
	$(OBJDIR)/src/lib/util/coreutil.o \
	$(OBJDIR)/src/lib/util/delegate.o \
	$(OBJDIR)/src/lib/util/disasmintf.o \
	$(OBJDIR)/src/lib/util/dynamicclass.o \
	$(OBJDIR)/src/lib/util/flac.o \
	$(OBJDIR)/src/lib/util/harddisk.o \
	$(OBJDIR)/src/lib/util/hash.o \
	$(OBJDIR)/src/lib/util/hashing.o \
	$(OBJDIR)/src/lib/util/huffman.o \
	$(OBJDIR)/src/lib/util/ioprocs.o \
	$(OBJDIR)/src/lib/util/ioprocsfilter.o \
	$(OBJDIR)/src/lib/util/jedparse.o \
	$(OBJDIR)/src/lib/util/language.o \
	$(OBJDIR)/src/lib/util/md5.o \
	$(OBJDIR)/src/lib/util/msdib.o \
	$(OBJDIR)/src/lib/util/nanosvg.o \
	$(OBJDIR)/src/lib/util/opresolv.o \
	$(OBJDIR)/src/lib/util/options.o \
	$(OBJDIR)/src/lib/util/palette.o \
	$(OBJDIR)/src/lib/util/path.o \
	$(OBJDIR)/src/lib/util/path_to_regex.o \
	$(OBJDIR)/src/lib/util/plaparse.o \
	$(OBJDIR)/src/lib/util/png.o \
	$(OBJDIR)/src/lib/util/strformat.o \
	$(OBJDIR)/src/lib/util/timeconv.o \
	$(OBJDIR)/src/lib/util/un7z.o \
	$(OBJDIR)/src/lib/util/unicode.o \
	$(OBJDIR)/src/lib/util/unzip.o \
	$(OBJDIR)/src/lib/util/vbiparse.o \
	$(OBJDIR)/src/lib/util/vecstream.o \
	$(OBJDIR)/src/lib/util/wavwrite.o \
	$(OBJDIR)/src/lib/util/xmlfile.o \
	$(OBJDIR)/src/lib/util/zippath.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug)
  OBJDIR              = obj/Debug
  TARGETDIR           = ../../../../../scripts/src
  override TARGET              = $(TARGETDIR)/libutils.a
  DEFINES            += -DMAME_DEBUG -DMAME_PROFILER -DCRLF=2 -DLSB_FIRST -DFLAC__NO_DLL -DPUGIXML_HEADER_ONLY -DLUA_COMPAT_ALL -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -DUTF8PROC_STATIC
  INCLUDES           += -I"../../../../../src/osd" -I"../../../../../src/lib/util" -I"../../../../../3rdparty" -I"../../../../../3rdparty/expat/lib" -I"../../../../../3rdparty/zlib" -I"../../../../../3rdparty/libflac/include" -I"../../../../../3rdparty/utf8proc"
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -pipe -Werror -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -Wno-error=attributes -Wno-format-overflow -Wno-stringop-truncation -Wno-stringop-overflow -Wno-return-local-addr
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -pipe -Werror -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -Wno-error=attributes -Wno-format-overflow -Wno-stringop-truncation -Wno-stringop-overflow -Wno-return-local-addr -std=gnu99 -Wpointer-arith -Wstrict-prototypes -Wbad-function-cast
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -std=c++17 -pipe -Werror -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -Wno-error=attributes -Wno-format-overflow -Wno-stringop-truncation -Wno-stringop-overflow -Wno-return-local-addr -std=c++17 -Woverloaded-virtual -Wimplicit-fallthrough -Wno-class-memaccess -Wsuggest-override -flifetime-dse=1
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -pipe -Werror -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -Wno-error=attributes -Wno-format-overflow -Wno-stringop-truncation -Wno-stringop-overflow -Wno-return-local-addr
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -std=c++17 -pipe -Werror -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -Wno-error=attributes -Wno-format-overflow -Wno-stringop-truncation -Wno-stringop-overflow -Wno-return-local-addr -std=c++17 -Wpointer-arith -Wimplicit-fallthrough
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -L"../../../../../../../../../usr/X11/lib" -L"../../../../../../../../../usr/X11R6/lib" -L"../../../../../../../../../usr/openwin/lib" -L"." -s
  LIBDEPS            +=
  LDDEPS             +=
  LDRESP              =
  LIBS               += $(LDDEPS) -ldl -lrt -lSDL2 -lm -lpthread -lutil
  EXTERNAL_LIBS      +=
  LINKOBJS            = $(OBJECTS)
  LINKCMD             = $(AR)  -rcs $(TARGET)
  OBJRESP             =
  OBJECTS := \
	$(OBJDIR)/src/lib/util/avhuff.o \
	$(OBJDIR)/src/lib/util/aviio.o \
	$(OBJDIR)/src/lib/util/bitmap.o \
	$(OBJDIR)/src/lib/util/cdrom.o \
	$(OBJDIR)/src/lib/util/chd.o \
	$(OBJDIR)/src/lib/util/chdcd.o \
	$(OBJDIR)/src/lib/util/chdcodec.o \
	$(OBJDIR)/src/lib/util/corealloc.o \
	$(OBJDIR)/src/lib/util/corefile.o \
	$(OBJDIR)/src/lib/util/corestr.o \
	$(OBJDIR)/src/lib/util/coreutil.o \
	$(OBJDIR)/src/lib/util/delegate.o \
	$(OBJDIR)/src/lib/util/disasmintf.o \
	$(OBJDIR)/src/lib/util/dynamicclass.o \
	$(OBJDIR)/src/lib/util/flac.o \
	$(OBJDIR)/src/lib/util/harddisk.o \
	$(OBJDIR)/src/lib/util/hash.o \
	$(OBJDIR)/src/lib/util/hashing.o \
	$(OBJDIR)/src/lib/util/huffman.o \
	$(OBJDIR)/src/lib/util/ioprocs.o \
	$(OBJDIR)/src/lib/util/ioprocsfilter.o \
	$(OBJDIR)/src/lib/util/jedparse.o \
	$(OBJDIR)/src/lib/util/language.o \
	$(OBJDIR)/src/lib/util/md5.o \
	$(OBJDIR)/src/lib/util/msdib.o \
	$(OBJDIR)/src/lib/util/nanosvg.o \
	$(OBJDIR)/src/lib/util/opresolv.o \
	$(OBJDIR)/src/lib/util/options.o \
	$(OBJDIR)/src/lib/util/palette.o \
	$(OBJDIR)/src/lib/util/path.o \
	$(OBJDIR)/src/lib/util/path_to_regex.o \
	$(OBJDIR)/src/lib/util/plaparse.o \
	$(OBJDIR)/src/lib/util/png.o \
	$(OBJDIR)/src/lib/util/strformat.o \
	$(OBJDIR)/src/lib/util/timeconv.o \
	$(OBJDIR)/src/lib/util/un7z.o \
	$(OBJDIR)/src/lib/util/unicode.o \
	$(OBJDIR)/src/lib/util/unzip.o \
	$(OBJDIR)/src/lib/util/vbiparse.o \
	$(OBJDIR)/src/lib/util/vecstream.o \
	$(OBJDIR)/src/lib/util/wavwrite.o \
	$(OBJDIR)/src/lib/util/xmlfile.o \
	$(OBJDIR)/src/lib/util/zippath.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release)
  OBJDIR              = obj/Release
  TARGETDIR           = ../../../../../scripts/src
  override TARGET              = $(TARGETDIR)/libutils.a
  DEFINES            += -DNDEBUG -DCRLF=2 -DLSB_FIRST -DFLAC__NO_DLL -DPUGIXML_HEADER_ONLY -DLUA_COMPAT_ALL -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -DUTF8PROC_STATIC
  INCLUDES           += -I"../../../../../src/osd" -I"../../../../../src/lib/util" -I"../../../../../3rdparty" -I"../../../../../3rdparty/expat/lib" -I"../../../../../3rdparty/zlib" -I"../../../../../3rdparty/libflac/include" -I"../../../../../3rdparty/utf8proc"
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -pipe -Werror -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -Wno-error=attributes -Wno-format-overflow -Wno-stringop-truncation -Wno-stringop-overflow -Wno-return-local-addr
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -pipe -Werror -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -Wno-error=attributes -Wno-format-overflow -Wno-stringop-truncation -Wno-stringop-overflow -Wno-return-local-addr -std=gnu99 -Wpointer-arith -Wstrict-prototypes -Wbad-function-cast
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -std=c++17 -pipe -Werror -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -Wno-error=attributes -Wno-format-overflow -Wno-stringop-truncation -Wno-stringop-overflow -Wno-return-local-addr -std=c++17 -Woverloaded-virtual -Wimplicit-fallthrough -Wno-class-memaccess -Wsuggest-override -flifetime-dse=1
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -pipe -Werror -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -Wno-error=attributes -Wno-format-overflow -Wno-stringop-truncation -Wno-stringop-overflow -Wno-return-local-addr
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -std=c++17 -pipe -Werror -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -Wno-error=attributes -Wno-format-overflow -Wno-stringop-truncation -Wno-stringop-overflow -Wno-return-local-addr -std=c++17 -Wpointer-arith -Wimplicit-fallthrough
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -L"../../../../../../../../../usr/X11/lib" -L"../../../../../../../../../usr/X11R6/lib" -L"../../../../../../../../../usr/openwin/lib" -L"." -s
  LIBDEPS            +=
  LDDEPS             +=
  LDRESP              =
  LIBS               += $(LDDEPS) -ldl -lrt -lSDL2 -lm -lpthread -lutil
  EXTERNAL_LIBS      +=
  LINKOBJS            = $(OBJECTS)
  LINKCMD             = $(AR)  -rcs $(TARGET)
  OBJRESP             =
  OBJECTS := \
	$(OBJDIR)/src/lib/util/avhuff.o \
	$(OBJDIR)/src/lib/util/aviio.o \
	$(OBJDIR)/src/lib/util/bitmap.o \
	$(OBJDIR)/src/lib/util/cdrom.o \
	$(OBJDIR)/src/lib/util/chd.o \
	$(OBJDIR)/src/lib/util/chdcd.o \
	$(OBJDIR)/src/lib/util/chdcodec.o \
	$(OBJDIR)/src/lib/util/corealloc.o \
	$(OBJDIR)/src/lib/util/corefile.o \
	$(OBJDIR)/src/lib/util/corestr.o \
	$(OBJDIR)/src/lib/util/coreutil.o \
	$(OBJDIR)/src/lib/util/delegate.o \
	$(OBJDIR)/src/lib/util/disasmintf.o \
	$(OBJDIR)/src/lib/util/dynamicclass.o \
	$(OBJDIR)/src/lib/util/flac.o \
	$(OBJDIR)/src/lib/util/harddisk.o \
	$(OBJDIR)/src/lib/util/hash.o \
	$(OBJDIR)/src/lib/util/hashing.o \
	$(OBJDIR)/src/lib/util/huffman.o \
	$(OBJDIR)/src/lib/util/ioprocs.o \
	$(OBJDIR)/src/lib/util/ioprocsfilter.o \
	$(OBJDIR)/src/lib/util/jedparse.o \
	$(OBJDIR)/src/lib/util/language.o \
	$(OBJDIR)/src/lib/util/md5.o \
	$(OBJDIR)/src/lib/util/msdib.o \
	$(OBJDIR)/src/lib/util/nanosvg.o \
	$(OBJDIR)/src/lib/util/opresolv.o \
	$(OBJDIR)/src/lib/util/options.o \
	$(OBJDIR)/src/lib/util/palette.o \
	$(OBJDIR)/src/lib/util/path.o \
	$(OBJDIR)/src/lib/util/path_to_regex.o \
	$(OBJDIR)/src/lib/util/plaparse.o \
	$(OBJDIR)/src/lib/util/png.o \
	$(OBJDIR)/src/lib/util/strformat.o \
	$(OBJDIR)/src/lib/util/timeconv.o \
	$(OBJDIR)/src/lib/util/un7z.o \
	$(OBJDIR)/src/lib/util/unicode.o \
	$(OBJDIR)/src/lib/util/unzip.o \
	$(OBJDIR)/src/lib/util/vbiparse.o \
	$(OBJDIR)/src/lib/util/vecstream.o \
	$(OBJDIR)/src/lib/util/wavwrite.o \
	$(OBJDIR)/src/lib/util/xmlfile.o \
	$(OBJDIR)/src/lib/util/zippath.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJDIRS := \
	$(OBJDIR) \
	$(OBJDIR)/src/lib/util \

RESOURCES := \

.PHONY: clean prebuild prelink

all: $(OBJDIRS) $(TARGETDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LIBDEPS) $(EXTERNAL_LIBS) $(RESOURCES) $(OBJRESP) $(LDRESP) | $(TARGETDIR) $(OBJDIRS)
	@echo Archiving $(notdir $@)...
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
endif
	$(SILENT) $(LINKCMD) $(LINKOBJS)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
	-$(call MKDIR,$(TARGETDIR))

$(OBJDIRS):
	-$(call MKDIR,$@)

clean:
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH) $(MAKEFILE) | $(OBJDIR)
	@echo Precompiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) -x c++-header $(DEFINES) $(INCLUDES) -o "$@" -c "$<"

$(GCH_OBJC): $(PCH) $(MAKEFILE) | $(OBJDIR)
	@echo Precompiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_OBJCPPFLAGS) -x objective-c++-header $(DEFINES) $(INCLUDES) -o "$@" -c "$<"
endif

ifneq (,$(OBJRESP))
$(OBJRESP): $(OBJECTS) | $(TARGETDIR) $(OBJDIRS)
	$(SILENT) echo $^
	$(SILENT) echo $^ > $@
endif

ifneq (,$(LDRESP))
$(LDRESP): $(LDDEPS) | $(TARGETDIR) $(OBJDIRS)
	$(SILENT) echo $^
	$(SILENT) echo $^ > $@
endif

$(OBJDIR)/src/lib/util/avhuff.o: ../../../../../src/lib/util/avhuff.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/aviio.o: ../../../../../src/lib/util/aviio.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/bitmap.o: ../../../../../src/lib/util/bitmap.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/cdrom.o: ../../../../../src/lib/util/cdrom.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/chd.o: ../../../../../src/lib/util/chd.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/chdcd.o: ../../../../../src/lib/util/chdcd.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/chdcodec.o: ../../../../../src/lib/util/chdcodec.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/corealloc.o: ../../../../../src/lib/util/corealloc.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/corefile.o: ../../../../../src/lib/util/corefile.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/corestr.o: ../../../../../src/lib/util/corestr.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/coreutil.o: ../../../../../src/lib/util/coreutil.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/delegate.o: ../../../../../src/lib/util/delegate.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/disasmintf.o: ../../../../../src/lib/util/disasmintf.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/dynamicclass.o: ../../../../../src/lib/util/dynamicclass.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/flac.o: ../../../../../src/lib/util/flac.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/harddisk.o: ../../../../../src/lib/util/harddisk.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/hash.o: ../../../../../src/lib/util/hash.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/hashing.o: ../../../../../src/lib/util/hashing.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/huffman.o: ../../../../../src/lib/util/huffman.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/ioprocs.o: ../../../../../src/lib/util/ioprocs.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/ioprocsfilter.o: ../../../../../src/lib/util/ioprocsfilter.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/jedparse.o: ../../../../../src/lib/util/jedparse.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/language.o: ../../../../../src/lib/util/language.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/md5.o: ../../../../../src/lib/util/md5.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/msdib.o: ../../../../../src/lib/util/msdib.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/nanosvg.o: ../../../../../src/lib/util/nanosvg.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/opresolv.o: ../../../../../src/lib/util/opresolv.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/options.o: ../../../../../src/lib/util/options.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/palette.o: ../../../../../src/lib/util/palette.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/path.o: ../../../../../src/lib/util/path.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/path_to_regex.o: ../../../../../src/lib/util/path_to_regex.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/plaparse.o: ../../../../../src/lib/util/plaparse.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/png.o: ../../../../../src/lib/util/png.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/strformat.o: ../../../../../src/lib/util/strformat.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/timeconv.o: ../../../../../src/lib/util/timeconv.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/un7z.o: ../../../../../src/lib/util/un7z.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/unicode.o: ../../../../../src/lib/util/unicode.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/unzip.o: ../../../../../src/lib/util/unzip.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/vbiparse.o: ../../../../../src/lib/util/vbiparse.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/vecstream.o: ../../../../../src/lib/util/vecstream.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/wavwrite.o: ../../../../../src/lib/util/wavwrite.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/xmlfile.o: ../../../../../src/lib/util/xmlfile.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/lib/util/zippath.o: ../../../../../src/lib/util/zippath.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/lib/util
	@echo Compiling $(subst ../,,$<)...
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(OBJDIR)/$(notdir $(PCH)).d
  -include $(OBJDIR)/$(notdir $(PCH))_objc.d
endif
